name: inventory_management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pocketbase: ^0.22.0
  shared_preferences: ^2.5.2
  path: ^ 1.9.1
  get: ^4.7.2
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  get_storage: ^2.1.1
  flutter_local_notifications: ^19.0.0
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
